pushd/popd fixes

diff --git a/tools/env-loader/action.yaml b/tools/env-loader/action.yaml
--- a/tools/env-loader/action.yaml
+++ b/tools/env-loader/action.yaml
@@ -43,7 +43,7 @@ runs:
         esac
 
         if [[ -z "${TOOL_VERSION}" ]]; then
-          TOOL_VERSION="${DEFAULT_TOOL_VERSION##tools/${TOOL_NAME}/}"
+          TOOL_VERSION="${DEFAULT_TOOL_VERSION##tools/"${TOOL_NAME}"/}"
         fi
 
         TAG="tools/${TOOL_NAME}/${TOOL_VERSION}"
@@ -78,9 +78,9 @@ runs:
         # `:` in the path name as a network address. Windows uses this to separate
         # drive/partition letter from file path, so this does not work on Windows. The
         # easiest workaround is just `pushd`/`popd`.
-        pushd "$(dirname "${DOWNLOAD_PATH}")"
+        pushd "$(dirname "${DOWNLOAD_PATH}")" || (echo "failed to change to download path" >&2; exit 1)
         maybe_sudo tar -xzf "$(basename "${DOWNLOAD_PATH}")" -C "${INSTALL_DIR}" "${TOOL_NAME}"
-        popd
+        popd || (echo "failed to leave the download path" >&2; exit 1)
         echo "${INSTALL_DIR}" >> "${GITHUB_PATH}"
         echo "Installation complete!"
 
